### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by arrrrr3186** [YasinShafiei/Handwritten-text-recognition#1]
Hello, 

where I can find the dataset?

Regards,

**Comment by ALIAHMAD419** [comment]
@arrrrr3186 did you find any dataset yet?

**Comment by YasinShafiei** [comment]
Hello
This is the link to the dataset :)
https://www.kaggle.com/datasets/ssarkar445/handwriting-recognitionocr

**Comment by aliahmad22419** [comment]
@YasinShafiei  i am new to Tensorflow after training the model i am trying to prediect the text and getting this Error:
`Traceback (most recent call last):
  File "/Users/aliahmad/Python/abc2.py", line 36, in <module>
    prediction_model = Model(inputs=full_model.get_layer(name="image").input, outputs=full_model.get_layer(name='output_dense').output)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aliahmad/Python/myenv/lib/python3.12/site-packages/keras/src/utils/tracking.py", line 26, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aliahmad/Python/myenv/lib/python3.12/site-packages/keras/src/models/functional.py", line 135, in __init__
    Function.__init__(self, inputs, outputs, name=name, **kwargs)
  File "/Users/aliahmad/Python/myenv/lib/python3.12/site-packages/keras/src/ops/function.py", line 62, in __init__
    raise ValueError(
ValueError: `inputs` argument cannot be empty. Received:
inputs=[]
outputs=<KerasTensor shape=(None, 50, 46), dtype=float32, sparse=False, name=keras_tensor_25>`
