### ISSUE TITLE
ValueError: `inputs` argument cannot be empty. Received:

### ISSUE THREAD

**Issue by aliahmad22419** [YasinShafiei/Handwritten-text-recognition#2]
`Traceback (most recent call last):
  File "/Users/abc/Python/main2.py", line 313, in <module>
    return filtered_texts
             ^^^^^^^^^^^^^
  File "/Users/aliahmad/Python/myenv/lib/python3.12/site-packages/keras/src/utils/tracking.py", line 26, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aliahmad/Python/myenv/lib/python3.12/site-packages/keras/src/models/functional.py", line 135, in __init__
    Function.__init__(self, inputs, outputs, name=name, **kwargs)
  File "/Users/aliahmad/Python/myenv/lib/python3.12/site-packages/keras/src/ops/function.py", line 62, in __init__
    raise ValueError(
ValueError: `inputs` argument cannot be empty. Received:
inputs=[]
outputs=<KerasTensor shape=(None, 50, 46), dtype=float32, sparse=False, name=keras_tensor_12>`

After training and saving the model when i am predicting the model. it says it's input arguments are empty.

**Comment by DontReb** [comment]
change the input "images" to "conv_1" as it is connected to "images" layer as well

**Comment by Sauravroy34** [comment]
try inputs=model.input[0], to get the input image layer
